const ASSIGNABLE_PACA_STUDENT_STATUSES = Object.freeze(['active', 'trial']);
const COMPLETED_TRIAL_PACA_STATUS = 'pending';
const ASSIGNMENT_SYNC_SOURCE_STATUSES = Object.freeze([
    ...ASSIGNABLE_PACA_STUDENT_STATUSES,
    COMPLETED_TRIAL_PACA_STATUS,
]);
const DEFAULT_TRIAL_TOTAL = 2;
const TRIAL_ASSIGNMENT_FLAG = 1;

module.exports = {
    ASSIGNABLE_PACA_STUDENT_STATUSES,
    ASSIGNMENT_SYNC_SOURCE_STATUSES,
    COMPLETED_TRIAL_PACA_STATUS,
    DEFAULT_TRIAL_TOTAL,
    TRIAL_ASSIGNMENT_FLAG,
};
